import { Fragment, createElement } from 'react';

const KOREAN_TERM_ANNOTATIONS: Readonly<Record<string, string>> = {
  '캐릭터': 'Character',
  '프리셋': 'Preset',
  '베이스': 'Base',
  '스페이스바': 'Spacebar',
  '게임패드': 'Gamepad',
  '키보드': 'Keyboard',
  '타임라인': 'Timeline',
  '오버레이': 'Overlay',
  '라이브러리': 'Library',
  '메타데이터': 'Metadata',
  '인터페이스': 'Interface',
  '프로젝트': 'Project',
  '미디어': 'Media',
  '커뮤니티': 'Community',
  '워터폴': 'Waterfall',
  '어빌리티': 'Ability',
  '피니셔': 'Finisher',
  '후딜레이': 'Recovery',
  '마우스': 'Mouse',
  '바인딩': 'Binding',
  '브라우저': 'Browser',
  '레이아웃': 'Layout',
  '스케일': 'Scale',
  '피드백': 'Feedback',
  '프롬프트': 'Prompt',
  '스페이스': 'Space',
  '시스템': 'System',
  '에디터': 'Editor',
  '캡처': 'Capture',
  '오디오': 'Audio',
  '아바타': 'Avatar',
  '온라인': 'Online',
  '게임플레이': 'Gameplay',
  '리액티브': 'Reactive',
  '트리거': 'Trigger',
  '트랜스코딩': 'Transcoding',
  '다운로드': 'Download',
  '업로드': 'Upload',
  '비디오': 'Video',
  '동영상': '動映像',
  '모듈': 'Module',
  '이미지': 'Image',
  '레이어': 'Layer',
  '아이콘': 'Icon',
  '캔버스': 'Canvas',
  '스타일': 'Style',
  '텍스트': 'Text',
  '프레임': 'Frame',
  '드래그': 'Drag',
  '테스트': 'Test',
  '데모': 'Demo',
  '리듬': 'Rhythm',
  '액션': 'Action',
  '캡슐': 'Capsule',
  '가이드': 'Guide',
  '매핑': 'Mapping',
  '차트': 'Chart',
  '블록': 'Block',
  '레인': 'Lane',
  '콤보': 'Combo',
  '마커': 'Marker',
  '폴더': 'Folder',
  '버튼': 'Button',
  '옵션': 'Option',
  '모드': 'Mode',
  '폰트': 'Font',
  '픽셀': 'Pixel',
  '파일': 'File',
  '세션': 'Session',
  '클릭': 'Click',
  '링크': 'Link',
  '태그': 'Tag',
  '에코': 'Echo',
  '줌': 'Zoom',
  '웹': 'Web',
  '앱': 'App',
  '키': 'Key',
  '불투명도': '不透明度',
  '상호작용': '相互作用',
  '사용자': '使用者',
  '편집기': '編輯器',
  '초기화': '初期化',
  '미지정': '未指定',
  '공명': '共鳴',
  '해방': '解放',
  '일반': '一般',
  '공격': '攻擊',
  '회피': '回避',
  '반응': '反應',
  '언어': '言語',
  '설정': '設定',
  '기록': '記錄',
  '중지': '中止',
  '동작': '動作',
  '선택': '選擇',
  '순서': '順序',
  '변경': '變更',
  '연습': '練習',
  '진행': '進行',
  '취소': '取消',
  '교체': '交替',
  '자유': '自由',
  '위치': '位置',
  '사용': '使用',
  '관리': '管理',
  '입력': '入力',
  '출력': '出力',
  '전환': '轉換',
  '시작': '始作',
  '종료': '終了',
  '표시': '表示',
  '내용': '內容',
  '영역': '領域',
  '간격': '間隔',
  '배경': '背景',
  '색상': '色相',
  '전체': '全體',
  '현재': '現在',
  '대상': '對象',
  '기본': '基本',
  '적용': '適用',
  '삭제': '削除',
  '추가': '追加',
  '저장': '貯藏',
  '복원': '復元',
  '실험': '實驗',
  '외관': '外觀',
  '도전': '挑戰',
  '시간': '時間',
  '지속': '持續',
  '판정': '判定',
  '축소': '縮小',
  '확대': '擴大',
  '축': '軸',
  '회차': '回次',
  '구간': '區間',
  '조정': '調整',
  '완료': '完了',
  '준비': '準備',
  '영상': '映像',
  '음량': '音量',
  '자동': '自動',
  '수평': '水平',
  '수직': '垂直',
  '투명': '透明',
  '회전': '回轉',
  '비율': '比率',
  '독립': '獨立',
  '전역': '全域',
  '할당': '割當',
  '연결': '連結',
  '복사': '複寫',
  '편집': '編輯',
  '실행': '實行',
  '오류': '誤謬',
  '실패': '失敗',
  '정보': '情報',
  '경로': '經路',
  '가능': '可能',
  '지원': '支援',
  '공간': '空間',
  '원본': '原本',
  '화면': '畫面',
  '최대': '最大',
  '최소': '最小',
  '확인': '確認',
  '효과': '效果',
  '상태': '狀態',
  '대기': '待機',
  '감지': '感知',
  '응답': '應答',
  '번호': '番號',
  '설명': '說明',
  '유형': '類型',
  '공유': '共有',
  '이동': '移動',
  '장치': '裝置',
  '속도': '速度',
  '범위': '範圍',
  '처리': '處理',
  '자료': '資料',
  '구성': '構成',
  '방식': '方式',
  '단계': '段階',
  '품질': '品質',
  '생성': '生成',
  '변환': '變換',
  '참조': '參照',
  '환경': '環境',
  '권한': '權限',
  '게임 패드': 'Gamepad',
  '미리보기': 'Preview',
  '미리 보기': 'Preview',
  '카운트다운': 'Countdown',
  '콘텐츠': 'Content',
  '타이밍': 'Timing',
  '오프셋': 'Offset',
  '인덱스': 'Index',
  '라운드': 'Round',
  '글로벌': 'Global',
  '로컬': 'Local',
  '커스텀': 'Custom',
  '스크롤': 'Scroll',
  '앵커': 'Anchor',
  '커서': 'Cursor',
  '페이드': 'Fade',
  '홈': 'Home',
  '메인': 'Main',
  '루프': 'Loop',
  '메모': 'Memo',
  '패딩': 'Padding',
  '빌드': 'Build',
  '신축성': '伸縮性',
  '낙하': '落下',
  '분할': '分割',
  '병합': '倂合',
  '배율': '倍率',
  '간편': '簡便',
  '극한': '極限',
  '제목': '題目',
  '재생': '再生',
  '정지': '停止',
  '일시': '一時',
  '음소거': '音消去',
  '배치': '配置',
  '고정': '固定',
  '여백': '餘白',
  '안내선': '案內線',
  '공백': '空白',
  '항목': '項目',
  '자산': '資産',
  '도구': '道具',
  '고급': '高級',
  '정의': '定義',
  '중심': '中心',
  '지점': '地點',
  '구분': '區分',
  '열': '列',
  '색': '色',
  '초': '秒',
  '회': '回',
  '개': '個',
  '중': '中',
  '비활성화': '非活性化',
  '활성화': '活性化',
  '불완전': '不完全',
  '직사각형': '直四角形',
  '데이터': 'Data',
  '사이즈': 'Size',
  '챌린지': 'Challenge',
  '런타임': 'Runtime',
  '트레이너': 'Trainer',
  '윈도우': 'Window',
  '볼륨': 'Volume',
  '에셋': 'Asset',
  '라벨': 'Label',
  '세트': 'Set',
  '트랙': 'Track',
  '로드': 'Load',
  '스킬': 'Skill',
  '점프': 'Jump',
  '활성': '活性',
  '확장': '擴張',
  '완전': '完全',
  '강도': '強度',
  '강공격': '強攻擊',
  '탐색': '探索',
  '변주': '變奏',
  '반주': '伴奏',
  '방향': '方向',
  '유지': '維持',
  '좌우': '左右',
  '제한': '制限',
  '해제': '解除',
  '특수': '特殊',
  '표준': '標準',
  '일치': '一致',
  '누락': '遺漏',
  '지정': '指定',
  '충분': '充分',
  '보관': '保管',
  '시도': '試圖',
  '발생': '發生',
  '목록': '目錄',
  '연동': '連動',
  '사전': '事前',
  '안내': '案內',
  '불가': '不可',
  '폭': '幅',
  '행': '行',
  '명조': '鳴潮',
  '황룡': '瑝瓏',
  '리나시타': 'Rinascita',
  '군성': '群星'
};

const KOREAN_TERM_PATTERN = new RegExp(
  Object.keys(KOREAN_TERM_ANNOTATIONS)
    .sort((left, right) => right.length - left.length)
    .map((term) => term.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'))
    .join('|'),
  'g'
);

export function annotateKoreanTerminology(value: string): string {
  const plainValue = String(value);
  KOREAN_TERM_PATTERN.lastIndex = 0;
  if (!KOREAN_TERM_PATTERN.test(plainValue)) return plainValue;
  return new KoreanRubyString(plainValue) as unknown as string;
}

type KoreanRubySegment = {
  text: string;
  annotation?: string;
};

function splitKoreanRubySegments(value: string): KoreanRubySegment[] {
  const segments: KoreanRubySegment[] = [];
  const pattern = new RegExp(KOREAN_TERM_PATTERN.source, 'g');
  let cursor = 0;
  let match: RegExpExecArray | null;

  while ((match = pattern.exec(value)) !== null) {
    if (match.index > cursor) segments.push({ text: value.slice(cursor, match.index) });
    const term = match[0];
    segments.push({ text: term, annotation: KOREAN_TERM_ANNOTATIONS[term] });
    cursor = match.index + term.length;
  }

  if (cursor < value.length) segments.push({ text: value.slice(cursor) });
  return segments;
}

function KoreanRubyText({ value }: { value: string }) {
  return createElement(
    Fragment,
    null,
    ...splitKoreanRubySegments(value).map((segment, index) => segment.annotation
      ? createElement('ruby', { key: `${index}-${segment.text}` }, segment.text, createElement('rt', null, segment.annotation))
      : segment.text)
  );
}

class KoreanRubyString extends String {
  constructor(value: string) {
    super(value);
    Object.assign(this, createElement(KoreanRubyText, { value }));
  }
}
